require("benjohn.core.colorscheme")
require("benjohn.core.options")
require("benjohn.core.keymaps")
require("benjohn.plugins-setup")
require("benjohn.plugins.comment")
require("benjohn.plugins.nvim-tree")
require("benjohn.plugins.lualine")
require("benjohn.plugins.telescope")
require("benjohn.plugins.nvim-cmp")
require("benjohn.plugins.lsp.mason")
require("benjohn.plugins.lsp.lspsaga")
require("benjohn.plugins.lsp.lspconfig")
require("benjohn.plugins.lsp.none-ls")
require("benjohn.plugins.autopairs")
require("benjohn.plugins.treesitter")
require("benjohn.plugins.gitsigns")
-- require("benjohn.plugins.lsp.rust_config")
require("benjohn.plugins.dap_config")
